{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1203.0 (24.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dBox\",\"dCalendario\",\"dHeadcount\",\"dHora\",\"dZona\",\"niveis\",\"fstatus_olpn_ed\",\"fstatus_olpn_periodic\",\"Medidas\",\"dHora_agora\",\"fpedidos_cancelados_ed\",\"fpedidos_cancelado_periodic\",\"fprodutividade_picking_periodic\",\"fprodutividade_picking_ed\",\"fprodutividade_putaway_periodic\",\"fprodutividade_putaway_ed\",\"fProdutividade\",\"fConferencia\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "fstatus_olpn_ed",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = PowerPlatform.Dataflows(null),",
          "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
          "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
          "    #\"b6308941-b395-4f22-b7a8-a4864f50baa0\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"b6308941-b395-4f22-b7a8-a4864f50baa0\"]}[Data],",
          "    fstatus_olpn_ed_ = #\"b6308941-b395-4f22-b7a8-a4864f50baa0\"{[entity=\"fstatus_olpn_ed\",version=\"\"]}[Data]",
          "in",
          "    fstatus_olpn_ed_"
        ],
        "kind": "m",
        "lineageTag": "3443db90-d597-46fb-988f-e3129131537e"
      },
      {
        "name": "fpedidos_cancelados_ed",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = PowerPlatform.Dataflows(null),",
          "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
          "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
          "    #\"4049e566-dc4d-4426-9ae0-5662fe4cd470\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"4049e566-dc4d-4426-9ae0-5662fe4cd470\"]}[Data],",
          "    fpedidos_cancelados_ed_ = #\"4049e566-dc4d-4426-9ae0-5662fe4cd470\"{[entity=\"fpedidos_cancelados_ed\",version=\"\"]}[Data]",
          "in",
          "    fpedidos_cancelados_ed_"
        ],
        "kind": "m",
        "lineageTag": "dd222e46-16a5-440d-a56c-cfe3ab5a97a6"
      },
      {
        "name": "fprodutividade_picking_ed",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = PowerPlatform.Dataflows(null),",
          "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
          "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
          "    #\"21df0c5d-25c1-4abb-9fb5-6ab9c8a5c399\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"21df0c5d-25c1-4abb-9fb5-6ab9c8a5c399\"]}[Data],",
          "    fprodutividade_picking_ed_ = #\"21df0c5d-25c1-4abb-9fb5-6ab9c8a5c399\"{[entity=\"fprodutividade_picking_ed\",version=\"\"]}[Data]",
          "in",
          "    fprodutividade_picking_ed_"
        ],
        "kind": "m",
        "lineageTag": "31eaea28-ff6f-4fee-ad01-2c21198a1583"
      },
      {
        "name": "fprodutividade_putaway_ed",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = PowerPlatform.Dataflows(null),",
          "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
          "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
          "    #\"b0e0eeb1-cdae-457c-b193-6633f439ac68\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"b0e0eeb1-cdae-457c-b193-6633f439ac68\"]}[Data],",
          "    fprodutividade_putaway_ed_ = #\"b0e0eeb1-cdae-457c-b193-6633f439ac68\"{[entity=\"fprodutividade_putaway_ed\",version=\"\"]}[Data]",
          "in",
          "    fprodutividade_putaway_ed_"
        ],
        "kind": "m",
        "lineageTag": "cdb45c04-4904-4ade-80ea-473acfad7737"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_9eaa23af-9487-4132-bd33-39fc2d7b816a",
        "fromColumn": "box",
        "fromTable": "fstatus_olpn_periodic",
        "toColumn": "box",
        "toTable": "dBox"
      },
      {
        "name": "cef644e4-cdee-2757-c655-97908faa85ec",
        "fromColumn": "data_olpn",
        "fromTable": "fstatus_olpn_periodic",
        "toColumn": "data",
        "toTable": "dCalendario"
      },
      {
        "name": "e5e630af-b459-e84a-43d8-d2d8d318edf8",
        "fromColumn": "hora_olpn",
        "fromTable": "fstatus_olpn_periodic",
        "toColumn": "hora",
        "toTable": "dHora"
      },
      {
        "name": "5e05203f-6b93-8333-da95-8d189f9c2ad9",
        "fromColumn": "local_picking",
        "fromTable": "fstatus_olpn_periodic",
        "toColumn": "local",
        "toTable": "dZona"
      },
      {
        "name": "b933fb66-4d30-9ed8-03be-14502de18953",
        "fromColumn": "nivelacao",
        "fromTable": "fstatus_olpn_periodic",
        "toColumn": "niveis",
        "toTable": "niveis"
      },
      {
        "name": "ed5e1a15-0232-3992-4742-275368614fe5",
        "fromColumn": "dt_cancelamento",
        "fromTable": "fpedidos_cancelado_periodic",
        "toColumn": "data",
        "toTable": "dCalendario"
      },
      {
        "name": "35b5155b-122c-6ad8-ffde-2995b3b88349",
        "fromColumn": "user",
        "fromTable": "fpedidos_cancelado_periodic",
        "toColumn": "user",
        "toTable": "dHeadcount"
      },
      {
        "name": "8600af43-37b0-f431-6189-36216b68a758",
        "fromColumn": "hora_cancelamento",
        "fromTable": "fpedidos_cancelado_periodic",
        "toColumn": "hora",
        "toTable": "dHora"
      },
      {
        "name": "3fe8b82b-d188-40d4-c204-fe8b029d8a52",
        "fromColumn": "nivel",
        "fromTable": "fprodutividade_picking_periodic",
        "toColumn": "niveis",
        "toTable": "niveis"
      },
      {
        "name": "AutoDetected_81c47695-061a-47eb-81cd-5d2cd30fc520",
        "fromColumn": "BOX",
        "fromTable": "fprodutividade_picking_periodic",
        "toColumn": "box",
        "toTable": "dBox"
      },
      {
        "name": "6ba73763-b01a-38ae-2171-b734638ff087",
        "fromColumn": "Data de Finalização da Tarefa",
        "fromTable": "fprodutividade_picking_periodic",
        "toColumn": "data",
        "toTable": "dCalendario"
      },
      {
        "name": "b5799a21-b225-412d-7200-c85a953337a5",
        "fromColumn": "Usuário",
        "fromTable": "fprodutividade_picking_periodic",
        "toColumn": "user",
        "toTable": "dHeadcount"
      },
      {
        "name": "fdba5d51-bfa8-afd2-d7b5-78f26c672d3c",
        "fromColumn": "Local de Coleta",
        "fromTable": "fprodutividade_picking_periodic",
        "toColumn": "local",
        "toTable": "dZona"
      },
      {
        "name": "284421bf-e08f-417a-7b50-3c45f008e102",
        "fromColumn": "Início da hora",
        "fromTable": "fprodutividade_picking_periodic",
        "toColumn": "hora",
        "toTable": "dHora"
      },
      {
        "name": "AutoDetected_b2fdeddf-df96-418e-8de0-f97d9bb5e6fd",
        "fromColumn": "box",
        "fromTable": "fprodutividade_putaway_periodic",
        "toColumn": "box",
        "toTable": "dBox"
      },
      {
        "name": "AutoDetected_b65a1668-7ed4-43fa-9645-42fe6a426f39",
        "fromColumn": "user",
        "fromTable": "fprodutividade_putaway_periodic",
        "toColumn": "user",
        "toTable": "dHeadcount"
      },
      {
        "name": "051393d1-d242-3e5a-6db7-32d4f7da50e7",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "oLPN",
        "fromTable": "fprodutividade_picking_periodic",
        "toColumn": "oLPN",
        "toTable": "fProdutividade"
      },
      {
        "name": "b458a6ae-c014-5da9-0549-aa42a1a18b8c",
        "fromColumn": "Data de Finalização da oLPN",
        "fromTable": "fProdutividade",
        "isActive": false,
        "toColumn": "data",
        "toTable": "dCalendario"
      },
      {
        "name": "1ec18366-e2bb-463c-9dd0-463861bf9a95",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "oLPN",
        "fromTable": "fprodutividade_picking_periodic",
        "toColumn": "OLPN",
        "toTable": "fConferencia"
      },
      {
        "name": "97fdd980-5dce-80bb-96f6-7fd007c2f850",
        "fromColumn": "Data LOAD",
        "fromTable": "fConferencia",
        "isActive": false,
        "toColumn": "data",
        "toTable": "dCalendario"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "dBox",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "box",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "be2c0a1e-6ec9-4889-a1dc-25c11b055fae",
            "sourceColumn": "box",
            "summarizeBy": "none"
          },
          {
            "name": "porta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d5b148b6-8f62-4c9e-8fa1-8f5f82f38b3d",
            "sourceColumn": "porta",
            "summarizeBy": "sum"
          },
          {
            "name": "setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79a7083c-978f-4442-a36a-debca6fab1c7",
            "sourceColumn": "setor",
            "summarizeBy": "none"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5823d7bd-ab15-4106-b396-88791ddf07d5",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "cubage_m3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c9b3b78e-ff63-40f8-876c-fab0a9c7449b",
            "sourceColumn": "cubage_m3",
            "summarizeBy": "sum"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "a9e58253-6282-47fb-aaf7-be6828713629",
        "partitions": [
          {
            "name": "dBox",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dBox_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dBox\",version=\"\"]}[Data]",
                "in",
                "    dBox_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "columns": [
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "01311786-8286-4894-87f8-39f89d312e25",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "9480ec97-572d-4aed-b919-3596456996a6",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Nome do mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf71b69b-77e4-4174-8621-5e0d40d8362c",
            "sortByColumn": "Mês",
            "sourceColumn": "Nome do mês",
            "summarizeBy": "none"
          },
          {
            "name": "Semana do mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "d0bfbec2-eeba-4967-b82c-a9ade63d3df8",
            "sourceColumn": "Semana do mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "e55f7ef0-498a-496b-945f-16dd52c7f6b3",
            "sourceColumn": "Dia",
            "summarizeBy": "sum"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d529a5f8-d3b8-4d7d-9288-071a7a1bc4a1",
            "sourceColumn": "Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Nome do dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7028cff3-3fd7-418b-9566-0e7a7182846d",
            "sourceColumn": "Nome do dia",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7ae7b956-7359-4cd9-8a31-09bf6893bbda",
            "sourceColumn": "Trimestre",
            "summarizeBy": "sum"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "5be52927-945a-4435-8b63-242e81b028f3",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dCalendario_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dCalendario\",version=\"\"]}[Data]",
                "in",
                "    dCalendario_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dHeadcount",
        "columns": [
          {
            "name": "user",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5474f2a6-6839-4b2f-aca4-dd03f6796468",
            "sourceColumn": "user",
            "summarizeBy": "none"
          },
          {
            "name": "nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "787df80e-c2ed-4aba-95c5-b22602fe82b2",
            "sourceColumn": "nome",
            "summarizeBy": "none"
          },
          {
            "name": "funcao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2281aedc-c246-483a-8420-a767e357c176",
            "sourceColumn": "funcao",
            "summarizeBy": "none"
          },
          {
            "name": "chefia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc8e675a-444a-4357-8ee9-526d072fc6f8",
            "sourceColumn": "chefia",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "d24c28e9-5fe9-4b7b-a7d6-30cfc53262ea",
        "partitions": [
          {
            "name": "dHeadcount",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dHeadcount_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dHeadcount\",version=\"\"]}[Data]",
                "in",
                "    dHeadcount_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dHora",
        "columns": [
          {
            "name": "hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "82510837-eb85-4c1c-92be-da75fb637707",
            "sourceColumn": "hora",
            "summarizeBy": "none"
          },
          {
            "name": "hora_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a553aa65-3094-4966-8a09-d4e6887a55ae",
            "sourceColumn": "hora_num",
            "summarizeBy": "sum"
          },
          {
            "name": "minuto_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bf08669a-3cb4-4144-a318-c4e2299034ae",
            "sourceColumn": "minuto_num",
            "summarizeBy": "sum"
          },
          {
            "name": "segundo_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "526d4748-b945-4f9d-bf56-56d9c6d9fbd0",
            "sourceColumn": "segundo_num",
            "summarizeBy": "sum"
          },
          {
            "name": "am_pm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06eb9cdf-b792-4485-9582-d81253b1c196",
            "sourceColumn": "am_pm",
            "summarizeBy": "none"
          },
          {
            "name": "turno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c4c1ba5-988e-4dbe-a2ff-49a9e4fd8185",
            "sourceColumn": "turno",
            "summarizeBy": "none"
          },
          {
            "name": "hora_fechada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "67051138-3cbe-45b6-8ce7-0fcad84bbd81",
            "sourceColumn": "hora_fechada",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "31c16edf-bc81-4017-8700-bb1402c82408",
        "partitions": [
          {
            "name": "dHora",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dHora_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dHora\",version=\"\"]}[Data]",
                "in",
                "    dHora_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dZona",
        "columns": [
          {
            "name": "local",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "452b6698-ecaf-4008-83d3-70b518c15a36",
            "sourceColumn": "local",
            "summarizeBy": "none"
          },
          {
            "name": "zona",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "693445a7-1b89-4562-be89-c169dea4f9ad",
            "sourceColumn": "zona",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "c52e1011-b1c3-4d7e-b16f-5b47422470ba",
        "partitions": [
          {
            "name": "dZona",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dZona_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dZona\",version=\"\"]}[Data]",
                "in",
                "    dZona_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "niveis",
        "columns": [
          {
            "name": "niveis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4eab96e6-e827-4714-8c82-abf44c2812c6",
            "sourceColumn": "niveis",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "e292a6e7-a085-4193-8e37-e7e509f643ad",
        "partitions": [
          {
            "name": "niveis",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    niveis_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"niveis\",version=\"\"]}[Data]",
                "in",
                "    niveis_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fstatus_olpn_periodic",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "tipo_pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a954cd9f-f8fc-4982-8f32-d5f562eaff76",
            "sourceColumn": "tipo_pedido",
            "summarizeBy": "none"
          },
          {
            "name": "pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e305f0d6-ac10-4bfc-aa80-9b079e21df27",
            "sourceColumn": "pedido",
            "summarizeBy": "sum"
          },
          {
            "name": "data_olpn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "8986f7b6-c39d-4746-ade4-96517edc986e",
            "sourceColumn": "data_olpn",
            "summarizeBy": "none"
          },
          {
            "name": "tarefa_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1c6c2ad-ebe2-4990-b28d-93524d9e462b",
            "sourceColumn": "tarefa_status",
            "summarizeBy": "none"
          },
          {
            "name": "gp_tarefa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1e0eb5b-703d-450c-8ff7-7038ba535c91",
            "sourceColumn": "gp_tarefa",
            "summarizeBy": "none"
          },
          {
            "name": "sku",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6638111d-dfae-464a-bbb8-544c27907a25",
            "sourceColumn": "sku",
            "summarizeBy": "sum"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f95056f2-78b2-48b2-abc8-683d67e64be6",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "local_picking",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d6a5778-1c78-418c-a6b6-6a17ad440c3f",
            "sourceColumn": "local_picking",
            "summarizeBy": "none"
          },
          {
            "name": "qt_pcs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "76c68785-cae8-4f17-b808-dded82bc1d1c",
            "sourceColumn": "qt_pcs",
            "summarizeBy": "sum"
          },
          {
            "name": "vol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fe48f095-8246-4f96-956b-37ef6e438b36",
            "sourceColumn": "vol",
            "summarizeBy": "sum"
          },
          {
            "name": "status_olpn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40a39850-fd6a-45f2-b290-04dc036f483b",
            "sourceColumn": "status_olpn",
            "summarizeBy": "none"
          },
          {
            "name": "n_gaiola",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "791f515f-c91f-48ec-99ea-d5977f76009a",
            "sourceColumn": "n_gaiola",
            "summarizeBy": "none"
          },
          {
            "name": "box",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fed4dcae-d7c7-41d8-834d-7e32b9ae1d9a",
            "sourceColumn": "box",
            "summarizeBy": "none"
          },
          {
            "name": "dt_limite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "d87de4a3-c882-474d-96bd-a89f3bd8db5a",
            "sourceColumn": "dt_limite",
            "summarizeBy": "none"
          },
          {
            "name": "desc_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d34dcd1d-a84d-4b60-9133-93904d0df00b",
            "sourceColumn": "desc_setor",
            "summarizeBy": "none"
          },
          {
            "name": "hora_olpn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "7ac16e32-8e25-43db-92e7-61150c59fc4a",
            "sourceColumn": "hora_olpn",
            "summarizeBy": "none"
          },
          {
            "name": "sep_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbec4181-5f1c-4038-bbe2-c711a6711e87",
            "sourceColumn": "sep_setor",
            "summarizeBy": "none"
          },
          {
            "name": "galpao_or_par",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "843388d4-192f-4035-b93e-c4429d8acb99",
            "sourceColumn": "galpao_or_par",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_expedicao_aba",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d96d2bba-c93f-4fee-a18b-df7c477293b1",
            "sourceColumn": "tipo_expedicao_aba",
            "summarizeBy": "none"
          },
          {
            "name": "nivelacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b96b9330-ac38-46e1-a73e-131b26437bc4",
            "sourceColumn": "nivelacao",
            "summarizeBy": "none"
          },
          {
            "name": "etapa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5dece85-ec0e-4306-a663-72d4b297b8c7",
            "sourceColumn": "etapa",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cee3a91-e129-4926-837e-e8da5aa3a5fa",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "data_abteviada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9677cca-f9fe-42e0-a0ce-d97ff80cbedc",
            "sourceColumn": "data_abteviada",
            "summarizeBy": "none"
          },
          {
            "name": "rota_br_vvlog",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "149a74c8-3dc2-4e53-98de-7fbec539c3c1",
            "sourceColumn": "rota_br_vvlog",
            "summarizeBy": "none"
          },
          {
            "name": "expansao_sep_setor_leves",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5dcaf1c-f4ec-44ae-93e2-50f83ef2e00e",
            "sourceColumn": "expansao_sep_setor_leves",
            "summarizeBy": "none"
          },
          {
            "name": "descricao_atividade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c61ec022-5112-41fb-927d-d4e646bf7008",
            "sourceColumn": "descricao_atividade",
            "summarizeBy": "none"
          },
          {
            "name": "Tarefa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87f933f9-4470-4fea-a0b2-5cce94a82e19",
            "sourceColumn": "Tarefa",
            "summarizeBy": "none"
          },
          {
            "name": "pedido_venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "272287dd-e611-47cc-985b-339eeeeae8aa",
            "sourceColumn": "pedido_venda",
            "summarizeBy": "sum"
          },
          {
            "name": "dt_pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7d69c784-749a-433d-98ff-b35ca5a2214d",
            "sourceColumn": "dt_pedido",
            "summarizeBy": "none"
          },
          {
            "name": "Wave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eddb4a96-1c36-4bbf-af29-d9f9233a27b0",
            "sourceColumn": "Wave",
            "summarizeBy": "none"
          },
          {
            "name": "atraso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f80b569-f41e-4a01-8136-5adf0bc5d931",
            "sourceColumn": "atraso",
            "summarizeBy": "none"
          },
          {
            "name": "oLPN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd55c3cc-d24f-49a1-8294-8a577bfb54a5",
            "sourceColumn": "oLPN",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d15d9ef1-dbc8-461b-a7f3-6e65e1417022",
        "partitions": [
          {
            "name": "fstatus_olpn_periodic",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"adf2ffd7-8f24-4826-b848-a698c5c51b3b\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"adf2ffd7-8f24-4826-b848-a698c5c51b3b\"]}[Data],",
                "    fstatus_olpn_periodic_ = #\"adf2ffd7-8f24-4826-b848-a698c5c51b3b\"{[entity=\"fstatus_olpn_periodic\",version=\"\"]}[Data],",
                "    #\"Consulta Acrescentada\" = Table.Combine({fstatus_olpn_periodic_, fstatus_olpn_ed}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Consulta Acrescentada\", each ([sep_setor] = \"\" or [sep_setor] = \"Abastecimento de Lojas\" or [sep_setor] = \"Balanço\"))",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Coluna 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e197e799-eda7-4945-a73a-9e821096ab28",
            "sourceColumn": "Coluna 1",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "197c8b73-a04c-43de-9174-105764e0dbc0",
        "measures": [
          {
            "name": "nome_usuario_logado",
            "displayFolder": "Úteis",
            "expression": [
              "",
              "",
              "VAR UsuarioCompleto = USERPRINCIPALNAME()",
              "VAR UsuarioSemDominio = LEFT(UsuarioCompleto, SEARCH(\"@\", UsuarioCompleto, 1) - 1)",
              "VAR UsuarioComEspacos = SUBSTITUTE(UsuarioSemDominio, \".\", \" \")",
              "",
              "VAR PalavrasSeparadas = SUBSTITUTE(UsuarioComEspacos, \" \", \"|\")",
              "VAR ListaPalavras = ",
              "    ADDCOLUMNS(",
              "        GENERATESERIES(1, PATHLENGTH(PalavrasSeparadas)),",
              "        \"Palavra\", PATHITEM(PalavrasSeparadas, [Value])",
              "    )",
              "VAR NomeCapitalizado = ",
              "    CONCATENATEX(",
              "        ListaPalavras,",
              "        UPPER(LEFT([Palavra], 1)) & LOWER(MID([Palavra], 2, LEN([Palavra]))),",
              "        \" \"",
              "    )",
              "RETURN NomeCapitalizado"
            ],
            "lineageTag": "1c4abfef-acc7-4271-91d6-af70a95445bb"
          },
          {
            "name": "data_hora",
            "displayFolder": "Úteis",
            "expression": [
              "",
              "",
              "SELECTEDVALUE(dHora_agora[data])&\" \"&SELECTEDVALUE(dHora_agora[hora])"
            ],
            "lineageTag": "53b2952b-63d7-4955-afd1-db90fefb45c7"
          },
          {
            "name": "qt_movimentado_olpn_<>_balanco",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "",
              "// Não contém o balanço",
              "CALCULATE(",
              "SUM(fstatus_olpn_periodic[qt_pcs]),",
              "fstatus_olpn_periodic[sep_setor] <> \"Balanço\")"
            ],
            "formatString": "#,0",
            "lineageTag": "60e94bad-bbbb-4c9e-9377-6d7673ee99cf"
          },
          {
            "name": "qt_movimentado_balanco",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "",
              "// Apenas balanço",
              "CALCULATE(",
              "SUM(fstatus_olpn_periodic[qt_pcs]),",
              "fstatus_olpn_periodic[sep_setor] = \"Balanço\")"
            ],
            "formatString": "#,0",
            "lineageTag": "fbdffed9-d04b-44cf-a4d7-36f1c0b88103"
          },
          {
            "name": "qt_cancelamentos",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "",
              "SUM(fpedidos_cancelado_periodic[qt_pcs])",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "186f7b4e-b78f-48b7-9c07-1aa7955ab112"
          },
          {
            "name": "performance_%",
            "displayFolder": "Performances",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              " 1 - DIVIDE([qt_cancelamentos],[qt_movimentado_olpn_<>_balanco]),",
              " ALL(dZona[zona]",
              "))",
              "",
              "VAR B = ",
              "IF(A <= 0 , \"\" , A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7f4a96ec-d192-43d9-ab91-80b178f8a2f9"
          },
          {
            "name": "calendario_din",
            "displayFolder": "Dinâmicos",
            "expression": [
              "",
              "",
              "[qt_movimentado_balanco] + [qt_movimentado_olpn_<>_balanco]"
            ],
            "formatString": "0",
            "lineageTag": "280b4ac5-c55d-4939-8f52-03b886d048f5"
          },
          {
            "name": "y_dinamico",
            "displayFolder": "Dinâmicos",
            "expression": [
              "",
              "",
              "MAXX(VALUES(dCalendario[Dia]), [qt_movimentado_balanco]+[qt_movimentado_olpn_<>_balanco]) * 2"
            ],
            "formatString": "0",
            "lineageTag": "6b40b565-b3b2-40da-a054-b0f625abc74f"
          },
          {
            "name": "qt_movimentada_geral",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "",
              "//contém balanço e geral",
              "",
              "[qt_movimentado_balanco]+[qt_movimentado_olpn_<>_balanco]"
            ],
            "formatString": "#,0",
            "lineageTag": "de60ffe6-e86c-42eb-8311-3fbe9abd9193"
          },
          {
            "name": "qt_movimentada_nivel_1_geral",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [qt_movimentada_geral],",
              "    fstatus_olpn_periodic[nivelacao] = \"Nível 1\")"
            ],
            "formatString": "#,0",
            "lineageTag": "d8cfc947-39aa-42b0-91c2-dd521c1f55a4"
          },
          {
            "name": "movimentado_por_setor",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    [qt_movimentada_geral],",
              "    ALL(fstatus_olpn_periodic[desc_setor]))",
              "",
              "",
              "RETURN",
              "[qt_movimentada_geral]/A"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b7ea8cae-05a6-426d-86f1-cfb240be2f8f"
          },
          {
            "name": "x_din",
            "displayFolder": "Dinâmicos",
            "expression": [
              "",
              "MAXX(VALUES(fstatus_olpn_periodic[desc_setor]),[qt_movimentada_geral]) * 2"
            ],
            "formatString": "0",
            "lineageTag": "571fac13-baa0-420a-b647-8d62fce1a030"
          },
          {
            "name": "media_diaria_movimentada",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR A =",
              "    DISTINCTCOUNT(fstatus_olpn_periodic[data_olpn])",
              "",
              "VAR B = ",
              "DIVIDE([qt_movimentada_geral],A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "#,0",
            "lineageTag": "e9e5b19f-a5e2-4c2c-8e92-d9af6469db07"
          },
          {
            "name": "media_diaria_movimentada_balanco",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR A =",
              "    DISTINCTCOUNT(fstatus_olpn_periodic[data_olpn])",
              "",
              "VAR B = ",
              "DIVIDE([qt_movimentado_balanco],A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "#,0",
            "lineageTag": "5de3a556-8dcc-412c-8de5-68c1929cba1b"
          },
          {
            "name": "media_diaria_movimentada<>balanco",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR A =",
              "    DISTINCTCOUNT(fstatus_olpn_periodic[data_olpn])",
              "",
              "VAR B = ",
              "DIVIDE([qt_movimentado_olpn_<>_balanco],A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "#,0",
            "lineageTag": "23f3d4d9-669f-4ef4-be94-103d510197aa"
          },
          {
            "name": "pico_movimentado",
            "displayFolder": "Picos e Vales",
            "expression": [
              "",
              "MAXX(VALUES(fstatus_olpn_periodic[data_olpn]),[qt_movimentada_geral])"
            ],
            "formatString": "#,0",
            "lineageTag": "cf663abf-d0b9-464b-947d-18302ddf2e1b"
          },
          {
            "name": "vale_movimentado",
            "displayFolder": "Picos e Vales",
            "expression": [
              "",
              "MINX(VALUES(fstatus_olpn_periodic[data_olpn]),[qt_movimentada_geral])"
            ],
            "formatString": "#,0",
            "lineageTag": "326b4e9c-2b40-4c5f-bdba-56a9074989ab"
          },
          {
            "name": "pico_movimentado_abastecimento",
            "displayFolder": "Picos e Vales",
            "expression": [
              "",
              "MAXX(VALUES(fstatus_olpn_periodic[data_olpn]),[qt_movimentado_olpn_<>_balanco])"
            ],
            "formatString": "#,0",
            "lineageTag": "8289c93f-f21a-45b0-9a88-a7dfa4f5966e"
          },
          {
            "name": "vale_movimentado_abastecimento",
            "displayFolder": "Picos e Vales",
            "expression": [
              "",
              "MINX(VALUES(fstatus_olpn_periodic[data_olpn]),[qt_movimentado_olpn_<>_balanco])"
            ],
            "formatString": "#,0",
            "lineageTag": "fae92e3c-4153-4445-98d7-35b8fc17ab8e"
          },
          {
            "name": "pico_movimentado_balanco",
            "displayFolder": "Picos e Vales",
            "expression": [
              "",
              "MAXX(VALUES(fstatus_olpn_periodic[data_olpn]),[qt_movimentado_balanco])"
            ],
            "formatString": "#,0",
            "lineageTag": "f6b503cf-b2b8-4174-88aa-d32aeab6dcaf"
          },
          {
            "name": "vale_movimentado_balanco",
            "displayFolder": "Picos e Vales",
            "expression": [
              "",
              "MINX(VALUES(fstatus_olpn_periodic[data_olpn]),[qt_movimentado_balanco])"
            ],
            "formatString": "#,0",
            "lineageTag": "3423e299-880e-411f-9803-9e79a41e54d3"
          },
          {
            "name": "pico_zona_movimentada",
            "displayFolder": "Picos e Vales",
            "expression": [
              "",
              "",
              "MAXX(VALUES(dZona[zona]),[qt_movimentada_geral])"
            ],
            "formatString": "#,0",
            "lineageTag": "f4dc14ad-7bc6-4f15-a2e5-18be5fc56e3b"
          },
          {
            "name": "vale_zona_movimentada",
            "displayFolder": "Picos e Vales",
            "expression": [
              "",
              "",
              "MINX(VALUES(dZona[zona]),[qt_movimentada_geral])"
            ],
            "formatString": "#,0",
            "lineageTag": "fac392df-19f6-4b1b-8a92-f96366c4ef21"
          },
          {
            "name": "media_hora_geral",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR A = ",
              "DISTINCTCOUNT(fstatus_olpn_periodic[hora_olpn])*DISTINCTCOUNT(fstatus_olpn_periodic[data_olpn])",
              "",
              "VAR B = ",
              "DIVIDE([qt_movimentada_geral],A)",
              "",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "#,0",
            "lineageTag": "c8d1d9ce-69ce-4e25-b34b-ecf272cf7dd2"
          },
          {
            "name": "media_hora_abastecimento",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR A = ",
              "DISTINCTCOUNT(fstatus_olpn_periodic[hora_olpn])*DISTINCTCOUNT(fstatus_olpn_periodic[data_olpn])",
              "",
              "VAR B = ",
              "DIVIDE([qt_movimentado_olpn_<>_balanco],A)",
              "",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "#,0",
            "lineageTag": "10e09669-6540-4470-a22f-867c17be55cc"
          },
          {
            "name": "media_hora_balanco",
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR A = ",
              "DISTINCTCOUNT(fstatus_olpn_periodic[hora_olpn])*DISTINCTCOUNT(fstatus_olpn_periodic[data_olpn])",
              "",
              "VAR B = ",
              "DIVIDE([qt_movimentado_balanco],A)",
              "",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "#,0",
            "lineageTag": "97ebceb8-c761-42a5-83c8-331076daf160"
          },
          {
            "name": "rank_cancelados",
            "displayFolder": "Top Cancelamentos",
            "expression": [
              "",
              "",
              "VAR A = ",
              "RANKX(",
              "    ALL(dHeadcount[nome]),",
              "    [qt_cancelamentos])",
              "",
              "VAR B = ",
              "SWITCH(",
              "    TRUE(),",
              "    A = 1 , \"👑1️⃣\",",
              "    A = 2 , \"👑2️⃣\",",
              "    A = 3 , \"👑3️⃣\",",
              "    A = 4 , \"4️⃣\",",
              "    A = 5 , \"5️⃣\",",
              "    A = 6 , \"6️⃣\",",
              "    A = 7 , \"7️⃣\",",
              "    A = 8 , \"8️⃣\",",
              "    A = 9 , \"9️⃣\",",
              "    A = 10 , \"🔟\",A)",
              "    ",
              "",
              "RETURN B",
              "    "
            ],
            "formatString": "0",
            "lineageTag": "4c08a706-a53e-4b58-bf97-4ef72e999988"
          },
          {
            "name": "x_rank_cancel",
            "displayFolder": "Top Cancelamentos",
            "expression": [
              "",
              "",
              "RANKX(",
              "    ALL(dHeadcount[nome]),",
              "    [qt_cancelamentos])"
            ],
            "formatString": "0",
            "lineageTag": "3b3cc947-8e3a-4d3f-9ef5-a3f2458a9ecc"
          },
          {
            "name": "valor_cancelado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-CO\"}"
              }
            ],
            "displayFolder": "Top Cancelamentos",
            "expression": [
              "",
              "SUM(fpedidos_cancelado_periodic[valor_rs])"
            ],
            "formatString": "\\$\\ #,0.00;-\\$\\ #,0.00;\\$\\ #,0.00",
            "lineageTag": "42cda452-711a-4a84-a134-a145e8f9e46d"
          },
          {
            "name": "hora_tratada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Lógica de Horas",
            "expression": [
              "",
              "",
              "VAR Total = ",
              "SUMX(DISTINCT(fprodutividade_picking_periodic[dif_second_task]),fprodutividade_picking_periodic[dif_second_task])",
              "",
              "",
              "VAR Horas = INT(Total/3600)",
              "",
              "VAR Modulo = MOD(Total,3600)",
              "",
              "VAR Minutos = INT(Modulo/60)",
              "",
              "VAR Segundos = MOD(Total,60)",
              "",
              "VAR Log_final = ",
              "Horas * 10000 +",
              "Minutos * 100 +",
              "Segundos",
              "",
              "RETURN",
              "Log_final"
            ],
            "formatString": "00:00:00",
            "lineageTag": "015fb8b8-ff31-4647-be68-59030977e7fc"
          },
          {
            "name": "comp_olpn_item",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comparações",
            "expression": [
              "",
              "DIVIDE(SUM(fprodutividade_picking_periodic[Qtde Separada]),DISTINCTCOUNT(fprodutividade_picking_periodic[oLPN]))"
            ],
            "lineageTag": "73cc1d3b-3d7d-49f2-8f78-471fd5cb7407"
          },
          {
            "name": "comp_item",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comparações",
            "expression": [
              "",
              "",
              "DIVIDE(",
              "    SUM(fprodutividade_picking_periodic[Qtde Separada]),",
              "    DISTINCTCOUNT(fprodutividade_picking_periodic[Item]))"
            ],
            "lineageTag": "1f5133d6-826d-43fd-aaa2-172e0aac6a46"
          },
          {
            "name": "comp_olpn",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comparações",
            "expression": [
              "",
              "",
              "DIVIDE(",
              "    SUM(fprodutividade_picking_periodic[Qtde Separada]),",
              "    DISTINCTCOUNT(fprodutividade_picking_periodic[oLPN]))"
            ],
            "lineageTag": "7800a501-b1ed-4238-9717-f13b398251f2"
          },
          {
            "name": "comp_tarefa",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comparações",
            "expression": [
              "",
              "",
              "DIVIDE(",
              "    SUM(fprodutividade_picking_periodic[Qtde Separada]),",
              "    DISTINCTCOUNT(fprodutividade_picking_periodic[Tarefa]))"
            ],
            "lineageTag": "3236255a-910b-47a5-9950-5c9aa8e4c29a"
          },
          {
            "name": "media_tarefa_base",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Lógica de Horas",
            "expression": [
              "",
              "",
              "VAR vhora = ",
              "SUMX(DISTINCT(fprodutividade_picking_periodic[dif_second_task]),fprodutividade_picking_periodic[dif_second_task])",
              "",
              "VAR Total    = ",
              "DIVIDE(",
              "    vhora,",
              "DISTINCTCOUNT(fprodutividade_picking_periodic[Tarefa]))",
              "",
              "VAR Horas = INT(Total/3600)",
              "",
              "VAR Modulo = MOD(Total,3600)",
              "",
              "VAR Minutos = INT(Modulo/60)",
              "",
              "VAR Segundos = MOD(Total,60)",
              "",
              "VAR Log_final = ",
              "Horas * 10000 +",
              "Minutos * 100 +",
              "Segundos",
              "",
              "RETURN",
              "Log_final"
            ],
            "formatString": "00:00:00",
            "lineageTag": "35f92d94-c722-4e8c-841f-ceb319d15e48"
          },
          {
            "name": "qt_movimentada_picking",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "SUM(fprodutividade_picking_periodic[Qtde Separada])"
            ],
            "formatString": "#,0",
            "lineageTag": "b15fdf6a-a7bb-4739-98bd-8b5059c8be9b"
          },
          {
            "name": "x_rank_pick",
            "displayFolder": "Top Movimentados",
            "expression": [
              "",
              "",
              "RANKX(",
              "    FILTER(",
              "        ALL(dHeadcount[nome]), ",
              "        NOT(ISBLANK(dHeadcount[nome]))",
              "    ),",
              "    [qt_movimentada_picking]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b7757da6-662d-4101-ad39-dd9b0efdd18b"
          },
          {
            "name": "rank_picking",
            "displayFolder": "Top Movimentados",
            "expression": [
              "",
              "",
              "VAR A = ",
              "RANKX(",
              "    FILTER(",
              "        ALL(dHeadcount[nome]), ",
              "        NOT(ISBLANK(dHeadcount[nome]))",
              "    ),",
              "    [qt_movimentada_picking]",
              ")",
              "",
              "VAR B = ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(dHeadcount[nome]) = BLANK(), \"\",",
              "    A = 1 , \"👑1️⃣\",",
              "    A = 2 , \"👑2️⃣\",",
              "    A = 3 , \"👑3️⃣\",",
              "    A = 4 , \"4️⃣\",",
              "    A = 5 , \"5️⃣\",",
              "    A = 6 , \"6️⃣\",",
              "    A = 7 , \"7️⃣\",",
              "    A = 8 , \"8️⃣\",",
              "    A = 9 , \"9️⃣\",",
              "    A = 10 , \"🔟\",A)",
              "    ",
              "",
              "RETURN B",
              "    "
            ],
            "formatString": "0",
            "lineageTag": "7a7a8514-3a6b-44d8-af96-b082d1ce8076"
          },
          {
            "name": "comparacao_media_atual",
            "displayFolder": "Comparações",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "[media_tarefa_base],",
              "ALL(dCalendario))",
              "",
              "VAR B = [media_tarefa_base]",
              "",
              "",
              "VAR C = (B/A) - 1",
              "",
              "VAR vC = ",
              "SWITCH(",
              "    TRUE(),",
              "    C > 0 , FORMAT(C,\"0%\")&\" \"&\"⬆️\",",
              "    C < 0 , FORMAT(C,\"0%\")&\" \"&\"⬇️\", C)",
              "",
              "VAR logica = ",
              "FORMAT(B, \"00:00:00\")&\"  \"&vC",
              "",
              "RETURN",
              "logica"
            ],
            "lineageTag": "0130dc3a-3edc-45e8-b54c-c6ec7575f1c3"
          },
          {
            "name": "media_confe_base",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR vhora = ",
              "SUMX(DISTINCT(fProdutividade[dif_confe]),fProdutividade[dif_confe])",
              "",
              "VAR Total    = ",
              "DIVIDE(",
              "    vhora,",
              "DISTINCTCOUNT(fProdutividade[oLPN]))",
              "",
              "VAR Horas = INT(Total/3600)",
              "",
              "VAR Modulo = MOD(Total,3600)",
              "",
              "VAR Minutos = INT(Modulo/60)",
              "",
              "VAR Segundos = MOD(Total,60)",
              "",
              "VAR Log_final = ",
              "Horas * 10000 +",
              "Minutos * 100 +",
              "Segundos",
              "",
              "RETURN",
              "Log_final"
            ],
            "formatString": "00:00:00",
            "lineageTag": "00aa9e72-7822-42ae-8d09-d012b271f233"
          },
          {
            "name": "comparacao_media_atual_conf",
            "displayFolder": "Comparações",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "[media_confe_base],",
              "ALL(dCalendario))",
              "",
              "VAR B = [media_confe_base]",
              "",
              "",
              "VAR C = (B/A) - 1",
              "",
              "VAR vC = ",
              "SWITCH(",
              "    TRUE(),",
              "    C > 0 , FORMAT(C,\"0%\")&\" \"&\"⬆️\",",
              "    C < 0 , FORMAT(C,\"0%\")&\" \"&\"⬇️\", C)",
              "",
              "RETURN",
              "FORMAT(B, \"00:00:00\")&\"  \"&vC"
            ],
            "lineageTag": "a833c400-33a7-4030-ac32-43ae890db4af"
          },
          {
            "name": "filter_din",
            "displayFolder": "Dinâmicos",
            "expression": [
              "",
              "",
              "SUM(fstatus_olpn_periodic[qt_pcs])",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "efe8e990-2a7e-4fe1-83e0-3b66f177d63c"
          },
          {
            "name": "time_lead",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Úteis",
            "expression": [
              "",
              "",
              "[media_tarefa_base]+[media_confe_base]+[media_confe_v2_base]"
            ],
            "formatString": "00:00:00",
            "lineageTag": "3cddfad5-d229-4877-aaae-a8a7a33545fe"
          },
          {
            "name": "media_confe_v2_base",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Médias",
            "expression": [
              "",
              "",
              "VAR vhora = ",
              "SUMX(DISTINCT(fConferencia[dif]),fConferencia[dif])",
              "",
              "VAR Total    = ",
              "DIVIDE(",
              "    vhora,",
              "DISTINCTCOUNT(fConferencia[oLPN]))",
              "",
              "VAR Horas = INT(Total/3600)",
              "",
              "VAR Modulo = MOD(Total,3600)",
              "",
              "VAR Minutos = INT(Modulo/60)",
              "",
              "VAR Segundos = MOD(Total,60)",
              "",
              "VAR Log_final = ",
              "Horas * 10000 +",
              "Minutos * 100 +",
              "Segundos",
              "",
              "RETURN",
              "Log_final"
            ],
            "formatString": "00:00:00",
            "lineageTag": "31ec2c77-278f-4459-9870-b23dfebe1e3e"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dHora_agora",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dc6d72f2-d41d-4875-b231-100b4a42f458",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "680594a8-930f-46b5-b895-7970096efc8c",
            "sourceColumn": "hora",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f2fb1131-6dc3-4823-96f1-35772ad16e85",
        "partitions": [
          {
            "name": "dHora_agora",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = DateTime.From(DateTime.LocalNow()) - #duration(0, 3, 0, 0),",
                "    #\"Convertido para Tabela\" = #table(1, {{Fonte}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Convertido para Tabela\",{{\"Column1\", \"hora\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"hora\", type datetime}}),",
                "  #\"Hora inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Hora (2)\", each DateTime.Time([hora]), type nullable time),",
                "  #\"Data calculada\" = Table.TransformColumns(#\"Hora inserida\", {{\"hora\", each DateTime.Date(_), type nullable date}}),",
                "  #\"Colunas renomeadas 1\" = Table.RenameColumns(#\"Data calculada\", {{\"hora\", \"data\"}, {\"Hora (2)\", \"hora\"}})",
                "in",
                "    #\"Colunas renomeadas 1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fpedidos_cancelado_periodic",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "287fae21-332b-4c58-ab35-00b1ed054f8b",
            "sourceColumn": "pedido",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09959095-4a28-4abd-aa8f-98067b7d7567",
            "sourceColumn": "tipo_pedido",
            "summarizeBy": "none"
          },
          {
            "name": "sku",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "14a7f605-0fd3-45ab-814c-9e7a2ca1fb9d",
            "sourceColumn": "sku",
            "summarizeBy": "sum"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60f4b0f7-bdea-4a4d-b377-47a54e79a728",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "qt_pcs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ddbcaa21-2f71-4625-925d-3f9f76a9d57d",
            "sourceColumn": "qt_pcs",
            "summarizeBy": "sum"
          },
          {
            "name": "dt_cancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a668f527-d380-4535-906e-f32230ee6c1e",
            "sourceColumn": "dt_cancelamento",
            "summarizeBy": "none"
          },
          {
            "name": "user",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb90e36c-1ae1-4752-aa9d-78801e6de071",
            "sourceColumn": "user",
            "summarizeBy": "none"
          },
          {
            "name": "desc_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a06476b1-c14f-4774-8759-6df41f9f3377",
            "sourceColumn": "desc_setor",
            "summarizeBy": "none"
          },
          {
            "name": "valor_rs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "21e09de4-e900-4277-a016-2efa45b8a8d8",
            "sourceColumn": "valor_rs",
            "summarizeBy": "sum"
          },
          {
            "name": "desc_cancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28f8435e-779a-48f0-a246-d79357104898",
            "sourceColumn": "desc_cancelamento",
            "summarizeBy": "none"
          },
          {
            "name": "hora_cancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "789c3cc6-6280-49be-ba64-4775ba88250e",
            "sourceColumn": "hora_cancelamento",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c02ec9fc-673c-4729-9761-c25a9af94203",
        "partitions": [
          {
            "name": "fpedidos_cancelado_periodic",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"04d51d01-463c-4055-af68-d72f0c19aa09\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"04d51d01-463c-4055-af68-d72f0c19aa09\"]}[Data],",
                "    fpedidos_cancelado_periodic_ = #\"04d51d01-463c-4055-af68-d72f0c19aa09\"{[entity=\"fpedidos_cancelado_periodic\",version=\"\"]}[Data],",
                "    #\"Consulta Acrescentada\" = Table.Combine({fpedidos_cancelado_periodic_, fpedidos_cancelados_ed}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Consulta Acrescentada\", each ([tipo_pedido] = \"\" or [tipo_pedido] = \"S13\" or [tipo_pedido] = \"S14\" or [tipo_pedido] = \"S46\" or [tipo_pedido] = \"S48\" or [tipo_pedido] = \"S53\"))",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fprodutividade_picking_periodic",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "sep_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5bf5680-743f-431d-9333-00fe99541b55",
            "sourceColumn": "sep_setor",
            "summarizeBy": "none"
          },
          {
            "name": "galpao_or_par",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe96e60b-f77c-475a-a408-9c1e62e84cad",
            "sourceColumn": "galpao_or_par",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_expedicao_aba",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d876549-c45f-4330-a1f5-c665472ed4a9",
            "sourceColumn": "tipo_expedicao_aba",
            "summarizeBy": "none"
          },
          {
            "name": "nivel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07182f7e-4296-451e-be0c-8db635197638",
            "sourceColumn": "nivel",
            "summarizeBy": "none"
          },
          {
            "name": "Tarefa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "413ea752-f2a6-410e-926e-24241be79349",
            "sourceColumn": "Tarefa",
            "summarizeBy": "none"
          },
          {
            "name": "Qtde Separada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f5026ec-60e0-4b99-88dd-1d9e2e69f4e6",
            "sourceColumn": "Qtde Separada",
            "summarizeBy": "sum"
          },
          {
            "name": "Wave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cae452ba-3aaf-4e79-b70c-96dde9c298d3",
            "sourceColumn": "Wave",
            "summarizeBy": "none"
          },
          {
            "name": "Usuário",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5033d054-fe56-4b4e-b003-ed2c5514d585",
            "sourceColumn": "Usuário",
            "summarizeBy": "none"
          },
          {
            "name": "Data do Inicio da Tarefa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e86099a8-b23d-49b3-ae85-972e95d4ae9c",
            "sourceColumn": "Data do Inicio da Tarefa",
            "summarizeBy": "none"
          },
          {
            "name": "Data de Finalização da Tarefa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "d7a691e9-d538-49dc-a34f-21459cad2a60",
            "sourceColumn": "Data de Finalização da Tarefa",
            "summarizeBy": "none"
          },
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fd83eacf-1924-4d11-8c10-9ab426f3f256",
            "sourceColumn": "Order ID",
            "summarizeBy": "count"
          },
          {
            "name": "oLPN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5da53d56-3b0f-4edb-a4bb-e6d9c4e1a6db",
            "sourceColumn": "oLPN",
            "summarizeBy": "none"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "109f5f7a-e8be-47b0-ab1d-75383e90e23a",
            "sourceColumn": "Item",
            "summarizeBy": "sum"
          },
          {
            "name": "Descrição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ba07b28-3fd7-417f-8f38-be03accb6c8e",
            "sourceColumn": "Descrição",
            "summarizeBy": "none"
          },
          {
            "name": "Setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ba7e5ca-b2f3-41af-9ff3-5b1a175f97f1",
            "sourceColumn": "Setor",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo de Pedido.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1858471-ebc7-4614-a874-ba4b2dd6e9c0",
            "sourceColumn": "Tipo de Pedido.1",
            "summarizeBy": "none"
          },
          {
            "name": "Local de Coleta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9be21498-84bb-4ebf-8f7e-f36d3939cee7",
            "sourceColumn": "Local de Coleta",
            "summarizeBy": "none"
          },
          {
            "name": "BOX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d5cffb90-574f-4479-bccd-3f3f7953f279",
            "sourceColumn": "BOX",
            "summarizeBy": "none"
          },
          {
            "name": "Início da hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "b1a40b8d-297b-4e7e-a861-405ed93023c6",
            "sourceColumn": "Início da hora",
            "summarizeBy": "none"
          },
          {
            "name": "dif_second_task",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "134c4297-fb63-4ffe-ad3f-080ab921111a",
            "sourceColumn": "dif_second_task",
            "summarizeBy": "sum"
          },
          {
            "name": "Data de Finalização da oLPN – Cópia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "721d4646-6f34-473a-bf69-b88a4f0d44da",
            "sourceColumn": "Data de Finalização da oLPN – Cópia",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "eef5f1d2-7e8f-4be7-a3ff-75c184af72db",
        "partitions": [
          {
            "name": "fprodutividade_picking_periodic",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"63f177c4-bbdc-47ac-a9d3-6ac6f66555ca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"63f177c4-bbdc-47ac-a9d3-6ac6f66555ca\"]}[Data],",
                "    fprodutividade_picking_periodic_ = #\"63f177c4-bbdc-47ac-a9d3-6ac6f66555ca\"{[entity=\"fprodutividade_picking_periodic\",version=\"\"]}[Data],",
                "    #\"Consulta Acrescentada\" = Table.Combine({fprodutividade_picking_periodic_, fprodutividade_picking_ed}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Consulta Acrescentada\", each ([sep_setor] = \"\" or [sep_setor] = \"Abastecimento de Lojas\" or [sep_setor] = \"Balanço\"))",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fprodutividade_putaway_periodic",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2bcb5895-b9da-407c-89cf-cbaaa67a0989",
            "sourceColumn": "pedido",
            "summarizeBy": "sum"
          },
          {
            "name": "status_olpn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ebc16ff-272d-4d78-905a-0e92b047c139",
            "sourceColumn": "status_olpn",
            "summarizeBy": "none"
          },
          {
            "name": "sku",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e464563d-6950-4f4f-8631-1b26f72018b4",
            "sourceColumn": "sku",
            "summarizeBy": "sum"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3edae22-c4d5-4d29-8e2c-63186a951927",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "qt_pc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8baa9ae9-ebd3-4c40-a7e4-dd7811607c66",
            "sourceColumn": "qt_pc",
            "summarizeBy": "sum"
          },
          {
            "name": "desc_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63e2e406-8c20-4c17-a48a-8fb796958d1b",
            "sourceColumn": "desc_setor",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6efc84a-c1f4-468b-aeaa-3fb08ae9367f",
            "sourceColumn": "tipo_pedido",
            "summarizeBy": "none"
          },
          {
            "name": "box",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "554be8bd-65be-473c-8003-c09250b01996",
            "sourceColumn": "box",
            "summarizeBy": "none"
          },
          {
            "name": "data_evento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4d3a49d5-5dcb-491f-af9f-34cc2e604d99",
            "sourceColumn": "data_evento",
            "summarizeBy": "none"
          },
          {
            "name": "user",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6476537e-bfac-49a5-ba15-00866039bfcb",
            "sourceColumn": "user",
            "summarizeBy": "none"
          },
          {
            "name": "hora_evento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "df8568d6-d0cc-4b8f-a132-efc571997e09",
            "sourceColumn": "hora_evento",
            "summarizeBy": "none"
          },
          {
            "name": "sep_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eab9c0a7-4187-468f-811b-07af6d178e28",
            "sourceColumn": "sep_setor",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_expedicao_aba",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00b7513c-a559-4426-8fb6-688bc2dbb814",
            "sourceColumn": "tipo_expedicao_aba",
            "summarizeBy": "none"
          },
          {
            "name": "dt_evento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4e683e8c-c097-4d61-9220-0cb4068ce372",
            "sourceColumn": "dt_evento",
            "summarizeBy": "none"
          },
          {
            "name": "OLPN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0fd16e45-6f19-46fb-94a6-553fd6662be4",
            "sourceColumn": "OLPN",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0054c7a3-37bb-4e8c-ab40-de1d5a71e16b",
        "partitions": [
          {
            "name": "fprodutividade_putaway_periodic",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"34a1a19b-cc55-4719-81a6-9fd86ddf056b\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"34a1a19b-cc55-4719-81a6-9fd86ddf056b\"]}[Data],",
                "    fprodutividade_putaway_periodic_ = #\"34a1a19b-cc55-4719-81a6-9fd86ddf056b\"{[entity=\"fprodutividade_putaway_periodic\",version=\"\"]}[Data],",
                "    #\"Consulta Acrescentada\" = Table.Combine({fprodutividade_putaway_periodic_, fprodutividade_putaway_ed}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Consulta Acrescentada\", each Date.IsInCurrentQuarter([data_evento]))",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fProdutividade",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "oLPN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc581930-7bbd-4a9a-8057-4918fbd74e52",
            "sourceColumn": "oLPN",
            "summarizeBy": "none"
          },
          {
            "name": "Data de Finalização da oLPN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "869c40e2-4b68-43e6-8320-f6accdbbb3b8",
            "sourceColumn": "Data de Finalização da oLPN",
            "summarizeBy": "none"
          },
          {
            "name": "dif_confe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0e0ea871-6729-46f6-9037-56fda07dbb7a",
            "sourceColumn": "dif_confe",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "239a7357-f497-4fb8-abe1-71fa9c0364f2",
        "partitions": [
          {
            "name": "fProdutividade",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"d03c098a-7e89-4897-8a99-12147927f95b\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"d03c098a-7e89-4897-8a99-12147927f95b\"]}[Data],",
                "    fProdutividade_ = #\"d03c098a-7e89-4897-8a99-12147927f95b\"{[entity=\"fProdutividade\",version=\"\"]}[Data]",
                "in",
                "    fProdutividade_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fConferencia",
        "columns": [
          {
            "name": "OLPN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "030b20cb-14ba-4431-992e-3b1b9722e14f",
            "sourceColumn": "OLPN",
            "summarizeBy": "none"
          },
          {
            "name": "Data LOAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "3e75f0e6-f1cb-4b28-9ad8-f9640d517f56",
            "sourceColumn": "Data LOAD",
            "summarizeBy": "none"
          },
          {
            "name": "dif",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "33341117-deb9-4c4a-acb3-ab8340810e94",
            "sourceColumn": "dif",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8196f306-ee99-4504-9317-58696c5433fc",
        "partitions": [
          {
            "name": "fConferencia",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"6a4b54d8-83db-499d-88ae-71aa78e2490d\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"6a4b54d8-83db-499d-88ae-71aa78e2490d\"]}[Data],",
                "    fConferencia_ = #\"6a4b54d8-83db-499d-88ae-71aa78e2490d\"{[entity=\"fConferencia\",version=\"\"]}[Data]",
                "in",
                "    fConferencia_"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}